// Generated by commsdsl2tools_qt v7.0.3

#include "MsgFactory.h"

#include "cc_tools_qt_plugin/Message/cc_mqtt5/message/Auth.h"
#include "cc_tools_qt_plugin/Message/cc_mqtt5/message/Connack.h"
#include "cc_tools_qt_plugin/Message/cc_mqtt5/message/Connect.h"
#include "cc_tools_qt_plugin/Message/cc_mqtt5/message/Disconnect.h"
#include "cc_tools_qt_plugin/Message/cc_mqtt5/message/Pingreq.h"
#include "cc_tools_qt_plugin/Message/cc_mqtt5/message/Pingresp.h"
#include "cc_tools_qt_plugin/Message/cc_mqtt5/message/Puback.h"
#include "cc_tools_qt_plugin/Message/cc_mqtt5/message/Pubcomp.h"
#include "cc_tools_qt_plugin/Message/cc_mqtt5/message/Publish.h"
#include "cc_tools_qt_plugin/Message/cc_mqtt5/message/Pubrec.h"
#include "cc_tools_qt_plugin/Message/cc_mqtt5/message/Pubrel.h"
#include "cc_tools_qt_plugin/Message/cc_mqtt5/message/Suback.h"
#include "cc_tools_qt_plugin/Message/cc_mqtt5/message/Subscribe.h"
#include "cc_tools_qt_plugin/Message/cc_mqtt5/message/Unsuback.h"
#include "cc_tools_qt_plugin/Message/cc_mqtt5/message/Unsubscribe.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_mqtt5
{

namespace factory
{

MsgFactory::MsgFactory() = default;
MsgFactory::~MsgFactory() = default;

MsgFactory::MessagesListInternal MsgFactory::createAllMessagesImpl()
{
    return
        MessagesListInternal{
            cc_tools_qt::ToolsMessagePtr(new cc_tools_qt_plugin::Message::cc_mqtt5::message::Connect),
            cc_tools_qt::ToolsMessagePtr(new cc_tools_qt_plugin::Message::cc_mqtt5::message::Connack),
            cc_tools_qt::ToolsMessagePtr(new cc_tools_qt_plugin::Message::cc_mqtt5::message::Publish),
            cc_tools_qt::ToolsMessagePtr(new cc_tools_qt_plugin::Message::cc_mqtt5::message::Puback),
            cc_tools_qt::ToolsMessagePtr(new cc_tools_qt_plugin::Message::cc_mqtt5::message::Pubrec),
            cc_tools_qt::ToolsMessagePtr(new cc_tools_qt_plugin::Message::cc_mqtt5::message::Pubrel),
            cc_tools_qt::ToolsMessagePtr(new cc_tools_qt_plugin::Message::cc_mqtt5::message::Pubcomp),
            cc_tools_qt::ToolsMessagePtr(new cc_tools_qt_plugin::Message::cc_mqtt5::message::Subscribe),
            cc_tools_qt::ToolsMessagePtr(new cc_tools_qt_plugin::Message::cc_mqtt5::message::Suback),
            cc_tools_qt::ToolsMessagePtr(new cc_tools_qt_plugin::Message::cc_mqtt5::message::Unsubscribe),
            cc_tools_qt::ToolsMessagePtr(new cc_tools_qt_plugin::Message::cc_mqtt5::message::Unsuback),
            cc_tools_qt::ToolsMessagePtr(new cc_tools_qt_plugin::Message::cc_mqtt5::message::Pingreq),
            cc_tools_qt::ToolsMessagePtr(new cc_tools_qt_plugin::Message::cc_mqtt5::message::Pingresp),
            cc_tools_qt::ToolsMessagePtr(new cc_tools_qt_plugin::Message::cc_mqtt5::message::Disconnect),
            cc_tools_qt::ToolsMessagePtr(new cc_tools_qt_plugin::Message::cc_mqtt5::message::Auth)
        };
}

} // namespace factory

} // namespace cc_mqtt5

} // namespace Message

} // namespace cc_tools_qt_plugin
