// Generated by commsdsl2tools_qt v8.0.0

/// @file
/// @brief Contains definition of the default options for plugin.

#pragma once

#include "cc_mqtt5/options/AllMessagesDynMemMsgFactoryDefaultOptions.h"
#include "cc_mqtt5/options/DefaultOptions.h"
#include "cc_tools_qt_plugin/cc_mqtt5/Version.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqtt5
{

namespace options
{

using DefaultOptions =
    ::cc_mqtt5::options::AllMessagesDynMemMsgFactoryDefaultOptionsT<
        ::cc_mqtt5::options::DefaultOptions
    >;

} // namespace options

} // namespace cc_mqtt5

} // namespace cc_tools_qt_plugin
