// Generated by commsdsl2tools_qt v6.3.3

#pragma once

#include <QtCore/QVariantMap>

namespace cc_tools_qt_plugin
{

namespace cc_mqtt5
{

namespace field
{

QVariantMap createProps_property(const char* name, bool serHidden = false);

} // namespace field

} // namespace cc_mqtt5

} // namespace cc_tools_qt_plugin
