// Generated by commsdsl2tools_qt v6.3.2

#include "Pingresp.h"

#include "cc_tools_qt/property/field.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqtt5
{

namespace message
{

namespace
{

QVariantList createProps()
{
    QVariantList props;
    return props;
}

} // namespace

Pingresp::Pingresp() = default;
Pingresp::~Pingresp() = default;
Pingresp& Pingresp::operator=(const Pingresp&) = default;
Pingresp& Pingresp::operator=(Pingresp&&) = default;

const QVariantList& Pingresp::fieldsPropertiesImpl() const
{
    static const QVariantList Props = createProps();
    return Props;
}

} // namespace message

} // namespace cc_mqtt5

} // namespace cc_tools_qt_plugin
