// Generated by commsdsl2tools_qt v6.3.2

#pragma once

#include <QtCore/QVariantList>
#include "cc_mqtt5/message/Pingresp.h"
#include "cc_tools_qt/ProtocolMessageBase.h"
#include "cc_tools_qt_plugin/cc_mqtt5/Message.h"
#include "cc_tools_qt_plugin/cc_mqtt5/options/DefaultOptions.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqtt5
{

namespace message
{

class Pingresp : public
    cc_tools_qt::ProtocolMessageBase<
        ::cc_mqtt5::message::Pingresp<cc_tools_qt_plugin::cc_mqtt5::Message, cc_tools_qt_plugin::cc_mqtt5::options::DefaultOptions>,
        Pingresp
    >
{
public:
    Pingresp();
    Pingresp(const Pingresp&) = delete;
    Pingresp(Pingresp&&) = delete;
    virtual ~Pingresp();
    Pingresp& operator=(const Pingresp&);
    Pingresp& operator=(Pingresp&&);

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override;
};

} // namespace message

} // namespace cc_mqtt5

} // namespace cc_tools_qt_plugin
