// Generated by commsdsl2tools_qt v6.3.0

#include "Plugin_CC_MQTT_v5.h"

#include "Protocol_CC_MQTT_v5.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqtt5
{

namespace plugin
{

Plugin_CC_MQTT_v5::Plugin_CC_MQTT_v5() :
    m_protocol(new Protocol_CC_MQTT_v5())
{
    pluginProperties()
        .setProtocolCreateFunc(
            [this]() noexcept -> cc_tools_qt::ProtocolPtr
            {
                return m_protocol;
            })
    ;
}

Plugin_CC_MQTT_v5::~Plugin_CC_MQTT_v5() = default;

} // namespace plugin

} // namespace cc_mqtt5

} // namespace cc_tools_qt_plugin
