// Generated by commsdsl2tools_qt v7.0.3

#include "Plugin_CC_MQTT_v5.h"

#include "Protocol_CC_MQTT_v5.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqtt5
{

namespace plugin
{

Plugin_CC_MQTT_v5::Plugin_CC_MQTT_v5() :
    Base(Type_Protocol)
{
}

Plugin_CC_MQTT_v5::~Plugin_CC_MQTT_v5() = default;

cc_tools_qt::ToolsProtocolPtr Plugin_CC_MQTT_v5::createProtocolImpl()
{
    return cc_tools_qt::ToolsProtocolPtr(new Protocol_CC_MQTT_v5());
}

} // namespace plugin

} // namespace cc_mqtt5

} // namespace cc_tools_qt_plugin
