// Generated by commsdsl2tools_qt v7.1.0

#include "Protocol_CC_MQTT_v5.h"

#include "cc_tools_qt_plugin/Message/cc_mqtt5/frame/Frame.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqtt5
{

namespace plugin
{

Protocol_CC_MQTT_v5::Protocol_CC_MQTT_v5() :
    Base(std::make_unique<cc_tools_qt_plugin::Message::cc_mqtt5::frame::Frame>())
{
}

Protocol_CC_MQTT_v5::~Protocol_CC_MQTT_v5() = default;

const QString& Protocol_CC_MQTT_v5::nameImpl() const
{
        static const QString Str("CC MQTT v5");
        return Str;
}

} // namespace plugin

} // namespace cc_mqtt5

} // namespace cc_tools_qt_plugin
