// Generated by commsdsl2tools_qt v6.3.3

#include "Protocol_CC_MQTT_v5.h"

#include <cassert>
#include "cc_tools_qt/ProtocolBase.h"
#include "cc_tools_qt_plugin/cc_mqtt5/frame/Frame.h"
#include "cc_tools_qt_plugin/cc_mqtt5/frame/FrameTransportMessage.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqtt5
{

namespace plugin
{

class Protocol_CC_MQTT_v5Impl : public
    cc_tools_qt::ProtocolBase<
        cc_tools_qt_plugin::cc_mqtt5::frame::Frame,
        cc_tools_qt_plugin::cc_mqtt5::frame::FrameTransportMessage
    >
{
    using Base =
        cc_tools_qt::ProtocolBase<
            cc_tools_qt_plugin::cc_mqtt5::frame::Frame,
            cc_tools_qt_plugin::cc_mqtt5::frame::FrameTransportMessage
        >;
public:
    friend class cc_tools_qt_plugin::cc_mqtt5::plugin::Protocol_CC_MQTT_v5;

    Protocol_CC_MQTT_v5Impl() = default;
    virtual ~Protocol_CC_MQTT_v5Impl() = default;

protected:
    virtual const QString& nameImpl() const override
    {
        static const QString Str("CC MQTT v5");
        return Str;
    }

    using Base::createInvalidMessageImpl;
    using Base::createRawDataMessageImpl;
    using Base::createExtraInfoMessageImpl;
};

Protocol_CC_MQTT_v5::Protocol_CC_MQTT_v5()
  : m_pImpl(new Protocol_CC_MQTT_v5Impl())
{
}

Protocol_CC_MQTT_v5::~Protocol_CC_MQTT_v5() = default;

const QString& Protocol_CC_MQTT_v5::nameImpl() const
{
    return m_pImpl->name();
}

Protocol_CC_MQTT_v5::MessagesList Protocol_CC_MQTT_v5::readImpl(const cc_tools_qt::DataInfo& dataInfo, bool final)
{
    return m_pImpl->read(dataInfo, final);
}

cc_tools_qt::DataInfoPtr Protocol_CC_MQTT_v5::writeImpl(cc_tools_qt::Message& msg)
{
    return m_pImpl->write(msg);
}

Protocol_CC_MQTT_v5::MessagesList Protocol_CC_MQTT_v5::createAllMessagesImpl()
{
    return m_pImpl->createAllMessages();
}

cc_tools_qt::MessagePtr Protocol_CC_MQTT_v5::createMessageImpl(const QString& idAsString, unsigned idx)
{
    return static_cast<cc_tools_qt::Protocol*>(m_pImpl.get())->createMessage(idAsString, idx);
}

Protocol_CC_MQTT_v5::UpdateStatus Protocol_CC_MQTT_v5::updateMessageImpl(cc_tools_qt::Message& msg)
{
    return m_pImpl->updateMessage(msg);
}

cc_tools_qt::MessagePtr Protocol_CC_MQTT_v5::cloneMessageImpl(const cc_tools_qt::Message& msg)
{
    return m_pImpl->cloneMessage(msg);
}

cc_tools_qt::MessagePtr Protocol_CC_MQTT_v5::createInvalidMessageImpl()
{
    return m_pImpl->createInvalidMessageImpl();
}

cc_tools_qt::MessagePtr Protocol_CC_MQTT_v5::createRawDataMessageImpl()
{
    return m_pImpl->createRawDataMessageImpl();
}

cc_tools_qt::MessagePtr Protocol_CC_MQTT_v5::createExtraInfoMessageImpl()
{
    return m_pImpl->createExtraInfoMessageImpl();
}

} // namespace plugin

} // namespace cc_mqtt5

} // namespace cc_tools_qt_plugin
