// Generated by commsdsl2tools_qt v7.0.2

#include "Message.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_mqtt5
{

Message::Message() = default;

Message::~Message() noexcept = default;

} // namespace cc_mqtt5

} // namespace Message

} // namespace cc_tools_qt_plugin
