// Generated by commsdsl2tools_qt v7.1.0

#pragma once

#include "cc_mqtt5/Message.h"
#include "cc_tools_qt/ToolsMessage.h"
#include "cc_tools_qt/ToolsProtMsgInterface.h"
#include "cc_tools_qt_plugin/cc_mqtt5/Version.h"
#include "cc_tools_qt_plugin/cc_mqtt5/options/DefaultOptions.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_mqtt5
{

class Message : public cc_tools_qt::ToolsMessage
{
public:
    using ProtInterface = cc_tools_qt::ToolsProtMsgInterface<::cc_mqtt5::Message>;
    using ProtOptions = cc_tools_qt_plugin::cc_mqtt5::options::DefaultOptions;
    Message();
    virtual ~Message() noexcept;
};

} // namespace cc_mqtt5

} // namespace Message

} // namespace cc_tools_qt_plugin
