// Generated by commsdsl2tools_qt v6.3.0

#pragma once

#include "cc_mqtt5/frame/Frame.h"
#include "cc_tools_qt_plugin/cc_mqtt5/Message.h"
#include "cc_tools_qt_plugin/cc_mqtt5/Version.h"
#include "cc_tools_qt_plugin/cc_mqtt5/input/AllMessages.h"
#include "cc_tools_qt_plugin/cc_mqtt5/options/MsgFactoryFrameOptions.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqtt5
{

namespace frame
{

using Frame =
    ::cc_mqtt5::frame::Frame<
        cc_tools_qt_plugin::cc_mqtt5::Message,
        cc_tools_qt_plugin::cc_mqtt5::input::AllMessages,
        cc_tools_qt_plugin::cc_mqtt5::options::MsgFactoryFrameOptions
    >;

} // namespace frame

} // namespace cc_mqtt5

} // namespace cc_tools_qt_plugin
